### ISSUE TITLE
New functions in EXTRA and new macro commands in the latest builds of Studio RM (1.4)

### ISSUE THREAD

**Issue by enozdrya** [truemoid/sublime-dm-macro#6]
New functions in EXTRA not highlighted
maxia(n1,n2,n3...)  - returns maximum while ignoring absent values
minia(n1,n2,n3...)  - return minimum while ignoring absent values

**Comment by alex-trueman** [comment]
Thanks. I have made the changes and published a new release. Sublime Text Package Control should push it through to you automatically within the day.
